/**
 * Device-related type definitions for RemoteOS.
 *
 * A "device" represents a physical computer running the RemoteOS agent.
 * Each device is uniquely identified and maintains a session with the relay server.
 */

// ─── Enums & Literals ──────────────────────────────────────────────

/** Device operating system */
export type DeviceOS = 'windows' | 'macos' | 'linux' | 'unknown';

/** Device connection lifecycle states */
export type DeviceStatus =
  | 'unregistered' // Agent installed but never paired
  | 'pending'      // Registration initiated, awaiting confirmation
  | 'online'       // Connected and ready
  | 'offline'      // Lost connection (no heartbeat)
  | 'busy'         // Executing a command
  | 'locked'       // Security lock engaged
  | 'error';       // Agent encountered a fatal error

/** Tier determines feature access */
export type DeviceTier = 'free' | 'pro' | 'team' | 'enterprise';

// ─── Device Info (static, set once at registration) ────────────────

/** Hardware and software information collected at registration */
export interface DeviceInfo {
  /** Unique device identifier (UUID v4, generated by agent) */
  id: string;
  /** Human-readable name (e.g., "Living Room PC") */
  name: string;
  /** Operating system */
  os: DeviceOS;
  /** OS version string (e.g., "Windows 11 23H2") */
  osVersion: string;
  /** Machine hostname */
  hostname: string;
  /** Agent software version (semver) */
  agentVersion: string;
  /** Internal IP address */
  localIp?: string;
  /** CPU model name */
  cpuModel?: string;
  /** Number of CPU cores */
  cpuCores?: number;
  /** Total RAM in GB */
  totalRamGb?: number;
  /** Total disk space in GB */
  totalDiskGb?: number;
  /** GPU model name */
  gpuModel?: string;
  /** Screen resolution */
  screenResolution?: string;
}

// ─── Device State (dynamic, updated via heartbeat) ─────────────────

/** Real-time system metrics snapshot */
export interface DeviceState {
  /** Device ID this state belongs to */
  deviceId: string;
  /** Current connection status */
  status: DeviceStatus;
  /** CPU usage percentage (0-100) */
  cpuUsage: number;
  /** RAM usage percentage (0-100) */
  ramUsage: number;
  /** Disk usage percentage (0-100) */
  diskUsage: number;
  /** CPU temperature in Celsius (null if unavailable) */
  cpuTemp: number | null;
  /** GPU temperature in Celsius (null if unavailable) */
  gpuTemp: number | null;
  /** Network download speed in Mbps */
  networkDownMbps: number;
  /** Network upload speed in Mbps */
  networkUpMbps: number;
  /** System uptime in seconds */
  uptimeSeconds: number;
  /** Number of running processes */
  processCount: number;
  /** Battery percentage (null if desktop/no battery) */
  batteryPercent: number | null;
  /** Whether the device is charging */
  isCharging: boolean | null;
  /** Currently active window title (if permitted) */
  activeWindow?: string;
  /** Timestamp of this snapshot */
  timestamp: Date;
}

// ─── Registration Flow ─────────────────────────────────────────────

/** Agent → Server: Register this device */
export interface DeviceRegisterRequest {
  /** Device hardware/software info */
  device: DeviceInfo;
  /** One-time registration token (from QR code or manual entry) */
  registrationToken: string;
}

/** Server → Agent: Registration result */
export interface DeviceRegisterResponse {
  success: boolean;
  /** Server-assigned device ID (may differ from agent-generated) */
  deviceId?: string;
  /** Persistent session token for future requests */
  sessionToken?: string;
  /** Token expiry timestamp */
  expiresAt?: Date;
  error?: string;
  /** Error code for programmatic handling */
  errorCode?: DeviceRegisterErrorCode;
}

export type DeviceRegisterErrorCode =
  | 'INVALID_TOKEN'
  | 'TOKEN_EXPIRED'
  | 'TOKEN_ALREADY_USED'
  | 'DEVICE_LIMIT_REACHED'
  | 'DUPLICATE_DEVICE'
  | 'INVALID_DEVICE_INFO';

// ─── Heartbeat ─────────────────────────────────────────────────────

/** Agent → Server: Periodic keep-alive with state */
export interface HeartbeatRequest {
  deviceId: string;
  sessionToken: string;
  state: DeviceState;
}

/** Server → Agent: Acknowledgment + pending work */
export interface HeartbeatResponse {
  acknowledged: boolean;
  /** Number of commands waiting in queue */
  pendingCommands: number;
  /** Server-side config updates (if any) */
  configUpdates?: Partial<AgentConfig>;
  /** Server timestamp for clock sync */
  serverTime: Date;
}

// ─── Agent Configuration (server can push updates) ─────────────────

/** Configuration that the server can push to agents */
export interface AgentConfig {
  /** Heartbeat interval in ms */
  heartbeatIntervalMs: number;
  /** Command poll interval in ms */
  pollIntervalMs: number;
  /** Command timeout in ms */
  commandTimeoutMs: number;
  /** Whether screenshot is allowed */
  allowScreenshot: boolean;
  /** Whether shell execution is allowed */
  allowShell: boolean;
  /** Maximum file download size in bytes */
  maxDownloadSizeBytes: number;
  /** Alert thresholds */
  alertThresholds: {
    cpuHigh: number;
    ramHigh: number;
    diskLow: number;
    tempHigh: number;
  };
}

// ─── Device Summary (for listing/dashboard) ────────────────────────

/** Lightweight device representation for lists */
export interface DeviceSummary {
  id: string;
  name: string;
  os: DeviceOS;
  status: DeviceStatus;
  /** Last heartbeat received at */
  lastSeenAt: Date | null;
  /** Current CPU usage (null if offline) */
  cpuUsage: number | null;
  /** Current RAM usage (null if offline) */
  ramUsage: number | null;
  /** User-defined label/tag */
  label?: string;
}
